apiVersion: v1
kind: Service
metadata:
  name: jcnr-mgmt
  labels:
    app: jcnr-mgmt
spec:
  clusterIP: None
  ports:
    - port: 50051
      name: jcnr-mgmt
  selector:
    app: jcnr-mgmt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jcnr-mgmt
  labels:
    app: jcnr-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jcnr-mgmt
  template:
    metadata:
      labels:
        app: jcnr-mgmt
    spec:
      containers:
      - name: jcnr-mgmt
        image: jcnr-mgmt
        ports:
        - containerPort: 50051
          name: http
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ""
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""     
          value: ""     
        - name: AWS_REGION
          value: "us-east-1"             
        - name: CLUSTERNAME
          value: ""
        - name: NODEGROUPS
          value: "one,two"          
        - name: NODENAMES
          value: "node1,node2"
        - name: INTFLIST
          value: "2,3" 
        - name: VPCID
          value: ""           
                   
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      # securityContext:
      #     privileged: true
      #     runAsUser: 0
