apiVersion: v1
kind: Service
metadata:
  name: jcnr-mgmt
  labels:
    app: jcnr-mgmt
spec:
  clusterIP: None
  ports:
    - port: 50051
      name: jcnr-mgmt
  selector:
    app: jcnr-mgmt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jcnr-mgmt
  labels:
    app: jcnr-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jcnr-mgmt
  template:
    metadata:
      labels:
        app: jcnr-mgmt
    spec:
      containers:
      - name: jcnr-mgmt
        image: jcnr-mgmt
        ports:
        - containerPort: 50051
          name: http
        env:
        - name: CLUSTERNAME
          value: "jcnrpvc-jcnrsrini-jcnr"
        - name: NODENAME
          value: "jcnr1"
        - name: INTFLIST
          value: "5" 
                   
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
          privileged: true
          runAsUser: 0
