apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: jcnr-mgmt
      context: jcnr-mgmt
      requires:
        - image: base
          alias: BASE
    - image: base
      context: base
manifests:
  rawYaml:
    - jcnr-mgmt/kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: jcnr-mgmt
    port: http
    localPort: 9001
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
