apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: jcnr-mgmt
build:
  artifacts:
    - image: jcnr-mgmt
      context: cmd/jcnr-mgmt
      requires:
        - image: base
          alias: BASE
    - image: base
      context: base 
manifests:
  rawYaml:
    - cmd/jcnr-mgmt/kubernetes/deployment.yaml
